package image;

import util.Matrices;

/**
 * Abstract class to reduce code duplication between classes for images generated by rasterisation
 */
public abstract class RasterImage extends ImageDuplicationLimiter {

    Pixel[][] pixels;

    /**
     * Checks the validity of an array
     * @param o : 2 dimension array to check
     */
    public void checkArrayValidity(Object[][] o) {
        Matrices.requiresNonZeroDimensions(o);
        Matrices.requiresNonNull(o);
        Matrices.requiresRectangularMatrix(o);
    }

    /**
     * Checks if a pixel is in an image
     * @param x : x pixel coordinate
     * @param y : y pixel coordinate
     * @return boolean checking if a pixel is contained in an image
     */
    public boolean areCoordinatesInArray(int x, int y) {
        return (x >= 0 && x < width) && (y >= 0 && y < height);
    }
}
